//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NLight.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NLight.Resources.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source argument contains duplicate keys..
        /// </summary>
        internal static string Collections_SourceCannotContainDuplicateKey {
            get {
                return ResourceManager.GetString("Collections_SourceCannotContainDuplicateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot fill a buffer and keep all its elements at the same time..
        /// </summary>
        internal static string Core_CannotKeepAllBufferElements {
            get {
                return ResourceManager.GetString("Core_CannotKeepAllBufferElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The member access expression does not access a property..
        /// </summary>
        internal static string Core_ExpressionDoesNotAccessProperty {
            get {
                return ResourceManager.GetString("Core_ExpressionDoesNotAccessProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid enumeration value..
        /// </summary>
        internal static string Core_InvalidEnumArgument {
            get {
                return ResourceManager.GetString("Core_InvalidEnumArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not an Enum type..
        /// </summary>
        internal static string Core_NotAnEnumType {
            get {
                return ResourceManager.GetString("Core_NotAnEnumType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression is not a member access expression..
        /// </summary>
        internal static string Core_NotMemberAccessExpression {
            get {
                return ResourceManager.GetString("Core_NotMemberAccessExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot move to a previous record in forward-only mode..
        /// </summary>
        internal static string IO_CannotMovePreviousRecordInForwardOnly {
            get {
                return ResourceManager.GetString("IO_CannotMovePreviousRecordInForwardOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A column named &apos;{0}&apos; was not found..
        /// </summary>
        internal static string IO_ColumnNotFound {
            get {
                return ResourceManager.GetString("IO_ColumnNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A column with the name &apos;{0}&apos; already exists..
        /// </summary>
        internal static string IO_DuplicateColumnName {
            get {
                return ResourceManager.GetString("IO_DuplicateColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record at index &apos;{0}&apos; appears to be corrupt. Current column index: &apos;{1}&apos;. Current position: &apos;{2}&apos;. Current raw data : &apos;{3}&apos;..
        /// </summary>
        internal static string IO_MalformedRecordException {
            get {
                return ResourceManager.GetString("IO_MalformedRecordException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one column must exists in the column collection. Columns may be added to the collection using the Columns property and its Add method..
        /// </summary>
        internal static string IO_NoColumnDefined {
            get {
                return ResourceManager.GetString("IO_NoColumnDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No current record..
        /// </summary>
        internal static string IO_NoCurrentRecord {
            get {
                return ResourceManager.GetString("IO_NoCurrentRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of fields in the record is greater than the available space from index to the end of the destination array..
        /// </summary>
        internal static string IO_NotEnoughSpaceInArray {
            get {
                return ResourceManager.GetString("IO_NotEnoughSpaceInArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid ParseErrorAction while inside a ParseError event..
        /// </summary>
        internal static string IO_ParseErrorActionInvalidInsideParseErrorEvent {
            get {
                return ResourceManager.GetString("IO_ParseErrorActionInvalidInsideParseErrorEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a supported ParseErrorAction..
        /// </summary>
        internal static string IO_ParseErrorActionNotSupported {
            get {
                return ResourceManager.GetString("IO_ParseErrorActionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no interface in the same network of the target IP address ({0}:{1}) for UDP listening..
        /// </summary>
        internal static string Net_NoInterfaceInSameNetwork {
            get {
                return ResourceManager.GetString("Net_NoInterfaceInSameNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence already completed..
        /// </summary>
        internal static string Reactive_SequenceAlreadyCompleted {
            get {
                return ResourceManager.GetString("Reactive_SequenceAlreadyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence already completed with an error..
        /// </summary>
        internal static string Reactive_SequenceAlreadyCompletedWithError {
            get {
                return ResourceManager.GetString("Reactive_SequenceAlreadyCompletedWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not convert &apos;{0}&apos; to type &apos;{1}&apos;..
        /// </summary>
        internal static string Text_CannotConvertToDataType {
            get {
                return ResourceManager.GetString("Text_CannotConvertToDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The conversion from type &apos;{0}&apos; to &apos;{1}&apos; is not supported..
        /// </summary>
        internal static string Text_ConversionNotSupported {
            get {
                return ResourceManager.GetString("Text_ConversionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The underlying thread (Name = &apos;{0}&apos;, ManagedThreadId = &apos;{1}&apos;) is no longer alive..
        /// </summary>
        internal static string Threading_UnderlyingThreadNotAlive {
            get {
                return ResourceManager.GetString("Threading_UnderlyingThreadNotAlive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested transaction context state transition to &apos;{1}&apos; is not coherent with the current state &apos;{0}&apos;..
        /// </summary>
        internal static string Transactions_IncoherentContextTransition {
            get {
                return ResourceManager.GetString("Transactions_IncoherentContextTransition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transaction context should be in one of the following states: {0}..
        /// </summary>
        internal static string Transactions_InvalidTransactionContextState {
            get {
                return ResourceManager.GetString("Transactions_InvalidTransactionContextState", resourceCulture);
            }
        }
    }
}
